---
seed: 42
output_folder_path: /content/drive/MyDrive/SkinFormer/Outputs/
#output_folder_path: /content/drive/MyDrive/UNSW/SkinFormer/Outputs/
root_image_dir: /content/drive/MyDrive/Datasets/Fitz17k/Images/
#root_image_dir: /content/drive/MyDrive/UNSW/Datasets/Fitz17k/Images/
Generated_csv_path: /content/drive/MyDrive/Datasets/Fitz17k/SkinFormer/fitapatrick17k_known_code.csv
#Generated_csv_path: /content/drive/MyDrive/UNSW/Datasets/Fitz17k/SkinFormer/fitapatrick17k_known_code.csv
num_workers: 1
default:
  batch_size: 64
  n_epochs: 20
  pretrained: True
  level: high
  n_classes: 3
  binary_subgroup: True