---
seed: 42
output_folder_path: /content/drive/MyDrive/SkinFormer/Outputs/LRP/
#output_folder_path: /content/drive/MyDrive/UNSW/SkinFormer/Outputs/LRP/
#output_folder_path: /content/drive/MyDrive/SkinFormer/Outputs/
#output_folder_path: /content/drive/MyDrive/UNSW/SkinFormer/Outputs/
root_image_dir: /content/drive/MyDrive/Datasets/Fitz17k/Images/
#root_image_dir: /content/drive/MyDrive/UNSW/Datasets/Fitz17k/Images/
Generated_csv_path: /content/drive/MyDrive/Datasets/Fitz17k/SkinFormer/fitapatrick17k_known_code.csv
#Generated_csv_path: /content/drive/MyDrive/UNSW/Datasets/Fitz17k/SkinFormer/fitapatrick17k_known_code.csv
num_workers: 1
default:
  batch_size: 64
  n_epochs: 50
  pretrained: True
  level: high
  binary_subgroup: False
prune:
  #main_br_path: /content/drive/MyDrive/UNSW/SkinFormer/Outputs/LRP/DeiT-S_LRP_checkpoint_BASE.pth
  main_br_path: /content/drive/MyDrive/SkinFormer/Outputs/LRP/DeiT-S_LRP_checkpoint_BASE.pth
  #SA_br_path: /content/drive/MyDrive/UNSW/SkinFormer/Outputs/LRP/DeiT-S_LRP_checkpoint_6SA_detection.pth
  SA_br_path: /content/drive/MyDrive/SkinFormer/Outputs/LRP/DeiT-S_LRP_checkpoint_6SA_detection.pth
  batch_size: 2
  binary_subgroup: False
  bias_metric_prev: 0.6284
  target_bias_metric: EOM
  num_batch_per_iter: 100
  max_consecutive_no_improvement: 5
  main_mask_quantile: 0.2  # (1- this param)% of the most important main params will be retained
  pruning_rate: 0.4        # showing the percentage of prunable parameters allowed by main branch to prune