Generated_csv_path: /home/ali/Datasets/Fitz17k/fitzpatrick17k_preprocessed.csv
dataset_name: Fitz17k
default:
  batch_size: 64
  level: high
  mode: train
  n_epochs: 50
  pretrained: true
num_workers: 1
output_folder_path: /home/ali/Outputs/Fitzpatrick17k/Pruning/Ablation_num/Iter1000_RR80_PR40/
prune:
  SA_br_path: /home/ali/Outputs/Fitzpatrick17k/XTranPrune_SABranch_Binary/DiT_S_LRP_2SABranch_checkpoint.pth
  SA_level: fitzpatrick_binary
  batch_size: 4
  bias_metric_prev: 0.628
  main_br_path: /home/ali/Outputs/Fitzpatrick17k/XTranPrune_baseline_High/DiT_S_LRP_level=high_checkpoint_BASE.pth
  main_level: high
  main_mask_retain_rate: 0.8
  max_consecutive_no_improvement: 5
  num_batch_per_iter: 1000
  pruning_rate: 0.4
  target_bias_metric: EOM
root_image_dir: /home/ali/Datasets/Fitz17k/Images/
seed: 42
