seed: 42
root_image_dir: /path_to/images/
Generated_csv_path: /path_to/PAD-UFES-20.csv
dataset_name: PAD                 # ["Fitz17k", "HIBA", "PAD"]
output_folder_path:
num_workers: 1
train:
  branch: main                        # ["main", "SA"]
  batch_size: 64
  main_level: low                    # [high, mid, low]
  SA_level: fitzpatrick_binary        # [fitzpatrick_binary, fitzpatrick]
  n_epochs: 100
  pretrained: True                                     # [True, False]
eval:
  weight_path: 
prune:
  main_br_path: 
  SA_br_path: 
  stratify_cols:
  - low
  - fitzpatrick
  sampler_type: CustomStratified                    # ["WeightedRandom", "Stratified", "CustomStratified"]
  target_bias_metric: EOM
  max_consecutive_no_improvement: 7
  batch_size: 4
  num_batch_per_iter: 70
  main_mask_retain_rate: 0.8
  pruning_rate: 0.4
  cont_method: transformer_attribution                # ["transformer_attribution", "attr", "grad", "attn", "TAM", AttrRoll", "FTaylor", "FTaylorpow2"]
  MaskUpdate_Type: AND                              # ["AND", "LAST"]
  BlockAgnosticMask: False                             # [True, False]
  verbose: 2                                          # [0, 1, 2] (more details as the number grows)
  