seed: 42
root_image_dir: /home/ali/Datasets/Fitz17k/Images/
Generated_csv_path: /home/ali/Datasets/Fitz17k/fitzpatrick17k_preprocessed.csv
output_folder_path: /home/ali/Outputs/Fitzpatrick17k/Pruning/Grad_method/
dataset_name: Fitz17k
num_workers: 1
default:
  batch_size: 64
  level: high
  mode: train
  n_epochs: 50
  pretrained: true
prune:
  main_br_path: /home/ali/Outputs/Fitzpatrick17k/XTranPrune_baseline_High/DiT_S_LRP_level=high_checkpoint_BASE.pth
  SA_br_path: /home/ali/Outputs/Fitzpatrick17k/XTranPrune_SABranch_Binary/DiT_S_LRP_2SABranch_checkpoint.pth
  SA_level: fitzpatrick_binary
  batch_size: 4
  bias_metric_prev: 0.628
  main_level: high
  main_mask_retain_rate: 0.8
  max_consecutive_no_improvement: 5
  num_batch_per_iter: 500
  pruning_rate: 0.4
  target_bias_metric: EOM
  method: grad                          # ["transformer_attribution", "attr", "grad"]
  verbose: 1