seed: 42
root_image_dir: /home/ali/Datasets/PAD-UFES-20/images/
Generated_csv_path: /home/ali/Datasets/PAD-UFES-20/PAD-UFES-20.csv
dataset_name: PAD
output_folder_path: /home/ali/Outputs/PAD-UFES-20/XTranPrune_sex/
num_workers: 1
default:
  batch_size: 64
  level: gender
  mode: train
  n_epochs: 70
  pretrained: true
prune:
  main_br_path: /home/ali/Outputs/Fitzpatrick17k/XTranPrune_baseline_High/DiT_S_LRP_level=high_checkpoint_BASE.pth
  SA_br_path: /home/ali/Outputs/Fitzpatrick17k/XTranPrune_SABranch_Binary/DiT_S_LRP_2SABranch_checkpoint.pth
  SA_level: fitzpatrick_binary
  main_level: high
  target_bias_metric: EOM
  bias_metric_prev: 0.628
  max_consecutive_no_improvement: 5
  batch_size: 4
  num_batch_per_iter: 500
  main_mask_retain_rate: 0.8
  pruning_rate: 0.4
  beta1: 0.85
  beta2: 0.85
  cont_method: grad                          # ["transformer_attribution", "attr", "grad", "attn"]
  method: normal                              # ['normal', 'MA', 'MA_Uncertainty']
  verbose: 1