seed: 42
root_image_dir: /home/ali/Datasets/Fitz17k/Images/
Generated_csv_path: /home/ali/Datasets/Fitz17k/fitzpatrick17k_preprocessed.csv
dataset_name: Fitz17k
output_folder_path: /home/ali/Outputs/Fitzpatrick17k/Pruning/Test_ME7/
num_workers: 1
default:
  batch_size: 64
  level: high
  mode: train
  n_epochs: 70
  pretrained: True                                     # [True, False]
prune:
  main_br_path: /home/ali/Outputs/Fitzpatrick17k/XTranPrune_baseline_High/DiT_S_LRP_level=high_checkpoint_BASE.pth
  SA_br_path: /home/ali/Outputs/Fitzpatrick17k/XTranPrune_SABranch_Binary/DiT_S_LRP_2SABranch_checkpoint.pth
  SA_level: fitzpatrick_binary
  main_level: high
  target_bias_metric: EOM
  bias_metric_prev: 0.628
  max_consecutive_no_improvement: 7
  batch_size: 4
  num_batch_per_iter: 500
  main_mask_retain_rate: 0.8
  pruning_rate: 0.4
  beta1: 0.25
  beta2: 0.25
  cont_method: transformer_attribution                # ["transformer_attribution", "attr", "grad", "attn"]
  method: MA_Uncertainty                              # ['normal', 'MA', 'MA_Uncertainty']
  normalize: True                                     # [True, False]
  verbose: 2                                          # [0, 1, 2] (more details as the number grows)