---
seed: 42
output_folder_path: /home/ali/Outputs/SkinFormer_baseline/
root_image_dir: /home/ali/Datasets/Fitz17k/Images/
Generated_csv_path: /home/ali/Datasets/Fitz17k/fitzpatrick17k_preprocessed.csv
num_workers: 1
default:
  mode: eval            # train, eval
  batch_size: 64
  n_epochs: 50
  pretrained: True      # True, False
  level: high           # level of label: low, mid, high, binary, fitzpatrick, or fitzpatrick_binary
prune:
  main_br_path: /content/drive/MyDrive/SkinFormer/Outputs/LRP/DeiT-S_LRP_checkpoint_BASE.pth
  SA_br_path: /content/drive/MyDrive/SkinFormer/Outputs/LRP/DeiT-S_LRP_checkpoint_6SA_detection.pth
  batch_size: 4
  binary_subgroup: False
  bias_metric_prev: 0.6284
  target_bias_metric: EOM
  num_batch_per_iter: 500
  max_consecutive_no_improvement: 5
  main_mask_quantile: 0.2  # (1- this param)% of the most important main params will be retained
  pruning_rate: 0.2        # showing the percentage of prunable parameters allowed by main branch to prune