seed: 42
root_image_dir: /home/ali/Datasets/PAD-UFES-20/images/
Generated_csv_path: /home/ali/Datasets/PAD-UFES-20/PAD-UFES-20.csv
dataset_name: PAD
output_folder_path: /home/ali/Outputs/PAD-UFES-20/Abblation/Attn/
num_workers: 1
default:
  batch_size: 64
  level: low
  mode: train
  n_epochs: 70
  pretrained: True                                     # [True, False]
prune:

  main_br_path: /home/ali/Outputs/PAD-UFES-20/XTranPrune_baseline_low/DiT_S_LRP_level=low_checkpoint_BASE.pth
  SA_br_path: /home/ali/Outputs/PAD-UFES-20/XTranPrune_SA_binary/DiT_S_LRP_2SABranch_checkpoint.pth
  SA_level: fitzpatrick_binary
  main_level: low
  target_bias_metric: EOM
  bias_metric_prev: 0.562
  max_consecutive_no_improvement: 6
  batch_size: 4
  num_batch_per_iter: 70
  main_mask_retain_rate: 0.8
  pruning_rate: 0.4
  beta1: 0.4
  beta2: 0.4
  cont_method: attn                # ["transformer_attribution", "attr", "grad", "attn", "TAM"]
  method: normal                              # ['normal', 'MA', 'MA_Uncertainty']
  verbose: 2                                          # [0, 1, 2] (more details as the number grows)