seed: 42
root_image_dir: /home/ali/Datasets/Harvard-GF3300/
train_csv_path: /home/ali/Datasets/Harvard-GF3300/train.csv
val_csv_path: /home/ali/Datasets/Harvard-GF3300/test.csv
dataset_name: GF3300                 # ["GF3300"]
output_folder_path: /home/ali/Outputs/GF3300/Contrastive_age_binary/MinDiff_MA_U_PR/RR80_PR40_B30_BA/
num_workers: 1
train:
  branch: main                        # ["main", "SA"]
  batch_size: 64
  main_level: glaucoma                    # [glaucoma]
  SA_level: age_binary        # [age_binary, age_multi, gender_binary, race_binary]
  n_epochs: 55
  pretrained: True                                     # [True, False]
# eval:
#   weight_path: 
prune:
  main_br_path: /home/ali/Outputs/GF3300/MainBranchBaseline/DiT_S_label=glaucoma_BEST_F1.pth
  SA_br_path: /home/ali/Outputs/GF3300/SABranchBaseline_age_binary/DiT_S_label=age_binary_BEST_F1.pth
  sampler_type: CustomStratified                    # ["WeightedRandom", "Stratified", "CustomStratified"]
  target_bias_metric: EOM
  max_consecutive_no_improvement: 7
  batch_size: 4
  num_batch_per_iter: 100
  main_mask_retain_rate: 0.8
  pruning_rate: 0.4
  beta1: 0.3
  beta2: 0.3
  cont_method: transformer_attribution                # ["transformer_attribution", "attr", "grad", "attn", "TAM", AttrRoll", "FTaylor", "FTaylorpow2"]
  method: MA_Uncertainty                                           # ['normal', 'MA', 'MA_Uncertainty']
  FObjective: MinDiff                                 # [MinDiff, MinJSD_Diff]
  MaskUpdate_Type: AND                              # ["AND", "LAST"]
  BlockAgnosticMask: True                             # [True, False]  
  apply_pagerank: True                               # [True, False]                 
  edge_type: attention_weights                        # ['attention_weights', 'gradients']
  aggr_type: outflow                                 # ['outflow', 'inflow', 'combined']
  redistribution_type: attention_weights             # ['attention_weights', 'original_ratio']
  PR_alpha: 0.85                                      # parameter Alpha used in the PageRank algorithm
  verbose: 2                                          # [0, 1, 2] (more details as the number grows)
  